# Generated by Django 6.0 on 2026-01-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacja', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widokbazyczlonkow',
            options={'managed': True, 'verbose_name': 'Widok Bazy Członków', 'verbose_name_plural': 'Widoki Bazy Członków'},
        ),
    ]
