# Generated by Django 6.0 on 2026-01-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacja', '0002_alter_widokbazyczlonkow_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='widokbazyczlonkow',
            name='data_aktualizacji',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='widokbazyczlonkow',
            name='telefon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='widokbazyczlonkow',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
